name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-8-jdk wget
        sudo apt-get install -y build-essential libssl-dev libffi-dev python3-dev
        pip install --upgrade pip
        pip install buildozer cython

    - name: Setup Android SDK
      run: |
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
        unzip -q commandlinetools-linux-7583922_latest.zip
        mkdir -p $HOME/android-sdk/cmdline-tools
        mv cmdline-tools $HOME/android-sdk/cmdline-tools/latest
        echo 'export ANDROID_HOME=$HOME/android-sdk' >> $GITHUB_ENV
        echo 'export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH' >> $GITHUB_ENV

    - name: Accept Android licenses
      run: |
        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
        yes | sdkmanager --licenses || true

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: flashcards-italiano-apk
        path: bin/*.apk
